apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: python-basic-170191021
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/hacdev/rpjimgpx-tenant/test-app-170191021/python-basic-170191021@sha256:5a0baf51d792e44ed3833590f55d5438b2881e189fd1f8a32f6104cd64b31f18
        name: my-python
        resources: {}
status: {}
