apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: python-basic-170191021
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: python-basic-170191021
    app.kubernetes.io/part-of: test-app-170191021
  name: python-basic-170191021
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: python-basic-170191021
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: python-basic-170191021
    spec:
      containers:
      - image: quay.io/hacdev/rpjimgpx-tenant/test-app-170191021/python-basic-170191021@sha256:5a0baf51d792e44ed3833590f55d5438b2881e189fd1f8a32f6104cd64b31f18
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
